### ISSUE TITLE
Response of feed submission is successful but item is not uploaded

### ISSUE THREAD

**Issue by themifycloud** [CPIGroup/phpAmazonMWS#105]
Hello mate,
i phpAmazonMWS/examples/feed_examples - > sendInventoryFeed()
to upload and item and getting the response message as:

    [FeedSubmissionId] => 51690017105
    [FeedType] => _POST_INVENTORY_AVAILABILITY_DATA_
    [SubmittedDate] => 2016-10-31T12:04:46+00:00
    [FeedProcessingStatus] => _SUBMITTED_

Note: But product is not visible in my inventory section on amazon store. What can be the issue???

**Comment by Peardian** [comment]
Amazon takes time to process feeds. You can use an `AmazonFeedList` object to check the status of your feeds and an `AmazonFeedResult` object to get the results once Amazon has finished processing it. More information on the process of using feeds/uploads should be available on Seller Central.

Since this question is really about Amazon MWS than the library itself, I'm going to close the issue.

**Comment by themifycloud** [comment]
feeds are showing the status of "DONE" but but is not appeared in amazon inventory yet. Image is attached. Thanks
![capture](https://cloud.githubusercontent.com/assets/8580808/19885358/63d1c772-9fdb-11e6-9d83-c3095b2aad10.PNG)

**Comment by Peardian** [comment]
Again, this question is more about Amazon's MWS service than the library itself. The fact that you were able to submit the feed and retrieve this information means that the library is working correctly. If you have questions about product listings or feed processing, please contact Amazon instead.
