### ISSUE TITLE
Merchant ID and Seller ID

### ISSUE THREAD

**Issue by ThomasRedstone** [CPIGroup/phpAmazonMWS#108]
MWS seems to only refer to Seller IDs, are these now the same thing? Or is the merchant ID carefully hidden somewhere?

The MWS scratchpad seems to only use Seller ID:

https://mws.amazonservices.co.uk/scratchpad/index.html

I'm having issues connecting so far, but don't know if this is the issue or not, either way it could use some clarification.

Thanks

**Comment by Peardian** [comment]
Yes, Merchant ID and Seller ID are the same thing. When I first started on the library, it was referred to as Merchant ID, but the name has since changed and that config option is now mapped to `SellerId`. As long as you follow the example config file, you should be able to connect fine.

I will have to remember to update the name when working on the new config system. Thank you for bringing it up.

**Comment by ThomasRedstone** [comment]
IT sounds like at some point, there were two IDs, but the APIs allowed them to be used interchangeably, and since that point, they have done away with one of them:

https://sellercentral.amazon.com/forums/thread.jspa?threadID=1797

Thanks for getting back so quickly and clarifying!
