### ISSUE TITLE
OrderItem

### ISSUE THREAD

**Issue by peppinoibra** [CPIGroup/phpAmazonMWS#122]
I have tried to achieve with the special functions the items in a certain order, but I get no response from the function, you could help me understand what's the problem?

```
function getAmazonItemOrders($ord) {
    require_once('../includes/classes.php'); //autoload classes, not needed if composer is being used
    try {
        $amz = new AmazonOrderItemList("Passiontech"); //store name matches the array key in the config file
        $amz->setOrderId($ord);
        $amz->setUseToken(); //tells the object to automatically use tokens right away
        return $amz->fetchItems(); //this is what actually sends the request
    } catch (Exception $ex) {
        echo 'There was a problem with the Amazon library. Error: '.$ex->getMessage();
    }
}
```

**Comment by Peardian** [comment]
Yes, I see what the problem is. The `fetchItems()` method indeed retrieves the items from Amazon, but it stores the data in the object and instead gives an indication of whether the operation was successful or not, as indicated by the PHPDoc. To access the data in the object, use the `getItems()` method.

If you have any questions about how to use a particular class, I recommend checking the PHPDoc at the top of the class file. For each class, I put information about which functions to use in the class and the order in which to use them.

**Comment by peppinoibra** [comment]
Thank you, it works.

**Comment by Peardian** [comment]
You're welcome. The whole library uses the same design, so hopefully you will find the rest of the library as easy to use.
