### ISSUE TITLE
Bad Response! 401 Unauthorized: AccessDenied

### ISSUE THREAD

**Issue by zootopia106** [CPIGroup/phpAmazonMWS#165]
I added my developer credentials correctly and even checked with the `/` at the end of the server url.
Currently, I am trying to test the order_example.php but it's continuously sending an error log like this:

[Info][2018/08/10 19:42:09 guest@cli AmazonOrderList.php:426 sendRequest] Making request to Amazon: ListOrders
[Urgent][2018/08/10 19:42:10 guest@cli AmazonOrderList.php:428 checkResponse] Bad Response! 401 Unauthorized: AccessDenied - Access to Orders.ListOrders is denied

Does anyone have similar experience before?
What's the reason of this bug?
Hope your favor.

**Comment by Peardian** [comment]
Sounds like a problem with the credentials. Since you are seeing the error message in the log, the library is doing its job correctly and there is not much else I can do for you here.

I found a link with information that might help you. If this link doesn't help you, I suggest asking for help on the official Amazon forums.

https://sellercentral.amazon.com/forums/t/troubleshooting-access-denied-errors/182386

**Comment by zootopia106** [comment]
Thanks @Peardian 
I will check that right now.
👍
