### ISSUE TITLE
Question Item Details

### ISSUE THREAD

**Issue by l0gical** [CPIGroup/phpAmazonMWS#33]
Hi,

Sorry for having to seek advice this way, I can't see any method on here for contacting you regarding a potentially simple question (apologies if this comes across as noob)
Do you have any examples for the Product Info [price] by any chance? if I could have asked directly then no problem paypal gifting something over.
I am trying to get to grips with obtaining pricing info of an ASIN, I can request the data and the function works, but unable to pull out specific values, if I print_r the variable then it does show the details amongst many other values.

Thanks in advance

Chris

**Comment by kossmokvin** [comment]
Could you please show the example of getting full product data?

I tried this: 
```
    require('../includes/classes.php'); //autoload classes, not needed if composer is being used
    try {
        $amz = new AmazonProductInfo("myStore"); 
        $amz->setASINs(array("B07H1W7XF1")); 
        $amz->fetchCategories(); 
        return $amz->getProduct(0)->getdata();
    } catch (Exception $ex) {
        echo 'There was a problem with the Amazon library. Error: '.$ex->getMessage();
    }   
```

and  as expected I have got data about categories ONLY.
How can I get the full product data? I cant find the fetch-method about that.. 
Please help =)

**Comment by Peardian** [comment]
@kossmokvin This issue is nearly four years old and is only tangentially related to your question. I will answer it this time, but if you have more questions or need further help, please make a new issue for it.

You will need to use the Reports API to get detailed product listing data, as the Products API only gives out limited, specific information. Check out the _AmazonReportRequest_ class for a list of available reports. Keep in mind that this library does not read the contents of reports, so you will have to parse the XML/TSV data yourself.
